# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, name:  { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', active: 't', created_by: 1, updated_by: 1)
AccountType.create(account_type: 'Asset', created_by: 1, updated_by: 1)
AccountType.create(account_type: 'Liability', created_by: 1, updated_by: 1)
AccountType.create(account_type: 'Equity', created_by: 1, updated_by: 1)
AccountType.create(account_type: 'Contra-Asset', created_by: 1, updated_by: 1)
AccountType.create(account_type: 'Contra-Liability', created_by: 1, updated_by: 1)
AccountType.create(account_type: 'Contra-Equity', created_by: 1, updated_by: 1)
#AccountType.create(account_type: 'Accounts Receivable', created_by: 1, updated_by: 1)
#AccountType.create(account_type: 'Inventory', created_by: 1, updated_by: 1)
#AccountType.create(account_type: 'Revenue', created_by: 1, updated_by: 1)
#AccountType.create(account_type: 'Operating Expense', created_by: 1, updated_by: 1)
#AccountType.create(account_type: 'Revenue', created_by: 1, updated_by: 1)
#AccountType.create(account_type: 'Revenue', created_by: 1, updated_by: 1)
Account.create(number: 1000, name: 'ASSETS', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1010, name: 'Cash Operating Account', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1020, name: 'Cash Debitors', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1030, name: 'Cash Petty Cash', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1200, name: 'RECEIVABLES', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1210, name: 'AR Trade', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1220, name: 'AR Trade Notes Receivable', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1230, name: 'AR Installment Receivables', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1240, name: 'AR Retainage Withheld', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1290, name: 'AR Allowance for Uncollectible Accounts', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1300, name: 'INVENTORIES', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1310, name: 'Inventory Reserved', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1320, name: 'Inventory Work-in-Progress', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1330, name: 'Inventory Finished Goods', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1340, name: 'Inventory Reservesd', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1350, name: 'Inventory Unbilled Cost & Fees', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1390, name: 'Inventory Reserve for Obsolescence', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1400, name: 'Prepaid EXPENSES OTHER CURRENT ASSETS', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1410, name: 'Prepaid Insurance', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1420, name: 'Prepaid Real Estate Taxes', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1430, name: 'Prepaid Repairs & Maintenance', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1440, name: 'Prepaid Rent', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1450, name: 'Prepaid Deposits', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1500, name: 'PROPERTY PLANT EQUIPMENT', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1510, name: 'PPE Buildings', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1520, name: 'PPE Machinery & Equipment', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1530, name: 'PPE Vehicles', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1540, name: 'PPE Computer Equipment', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1550, name: 'PPE Furniture & Fixtures', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1560, name: 'PPE Leasehold Improvements', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1600, name: 'ACCUMULATED DEPRECIATION AMORTIZATION', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1610, name: 'ACCUM DEPR Buildings', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1620, name: 'ACCUM DEPR Machinery Equipment', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1630, name: 'ACCUM DEPR Vehicles', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1640, name: 'ACCUM DEPR Computer Equipment', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1650, name: 'ACCUM DEPR Furniture Fixtures', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1660, name: 'ACCUM DEPR Leasehold Improvements', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1700, name: 'NON CURRENT RECEIVABLES', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1710, name: 'NCA Notes Receivable', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1720, name: 'NCA Installment Receivables', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1730, name: 'NCA Retainage Withheld', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1800, name: 'INTERCOMPANY RECEIVABLES', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1900, name: 'OTHER NON-CURRENT ASSETS', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1910, name: 'Organization Costs', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1920, name: 'Patents Licenses', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 1930, name: 'Intangible Assets Capitalized Software Costs', active: 't', created_by: 1, updated_by: 1, account_type_id: 1)
Account.create(number: 2000, name: 'LIABILITIES', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2100, name: 'PAYABLES', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2110, name: 'A/P Trade', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2120, name: 'A/P Accrued Accounts Payable', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2130, name: 'A/P Retainage Withheld', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2150, name: 'Current Maturities of Long-Term Debt', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2160, name: 'Bank Notes Payable', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2170, name: 'Construction Loans Payable', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2200, name: 'ACCRUED COMPENSATION RELATED ITEMS', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2210, name: 'Accrued Payroll', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2220, name: 'Accrued Commissions', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2230, name: 'Accrued FICA', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2240, name: 'Accrued Unemployment Taxes', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2250, name: 'Accrued Workmen.s Comp', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2260, name: 'Accrued Medical Benefits', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2270, name: 'Accrued 401 K Company Match', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2275, name: 'W/H FICA', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2280, name: 'W/H Medical Benefits', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2285, name: 'W/H 401 K Employee Contribution', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2300, name: 'OTHER ACCRUED EXPENSES', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2310, name: 'Accrued Rent', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2320, name: 'Accrued Interest', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2330, name: 'Accrued Property Taxes', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2340, name: 'Accrued Warranty Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2500, name: 'ACCRUED TAXES', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2510, name: 'Accrued Federal Income Taxes', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2520, name: 'Accrued State Income Taxes', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2530, name: 'Accrued Franchise Taxes', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2540, name: 'Deferred FIT Current', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2550, name: 'Deferred State Income Taxes', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2600, name: 'DEFERRED TAXES', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2610, name: 'D/T FIT . NON CURRENT', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2620, name: 'D/T SIT . NON CURRENT', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2700, name: 'LONG-TERM DEBT', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2710, name: 'LTD Notes Payable', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2720, name: 'LTD Mortgages Payable', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2730, name: 'LTD Installment Notes Payable', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2800, name: 'INTERCOMPANY PAYABLES', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 2900, name: 'OTHER NON CURRENT LIABILITIES', active: 't', created_by: 1, updated_by: 1, account_type_id: 2)
Account.create(number: 3000, name: 'OWNERS EQUITIES', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 3100, name: 'Common Stock', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 3200, name: 'Preferred Stock', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 3300, name: 'Paid in Capital', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 3400, name: 'Partners Capital', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 3500, name: 'Member Contributions', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 3900, name: 'Retained Earnings', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 4000, name: 'REVENUE', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 4010, name: 'REVENUE PRODUCT 1', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 4020, name: 'REVENUE PRODUCT 2', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 4030, name: 'REVENUE PRODUCT 3', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 4040, name: 'REVENUE PRODUCT 4', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 4600, name: 'Interest Income', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 4700, name: 'Other Income', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 4800, name: 'Finance Charge Income', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 4900, name: 'Sales Returns and Allowances', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 4950, name: 'Sales Discounts', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 5000, name: 'COST OF GOODS SOLD', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 5010, name: 'COGS PRODUCT 1', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 5020, name: 'COGS PRODUCT 2', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 5030, name: 'COGS PRODUCT 3', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 5040, name: 'COGS PRODUCT 4', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 5700, name: 'Freight', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 5800, name: 'Inventory Adjustments', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 5900, name: 'Purchase Returns and Allowances', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 5950, name: 'Reserved', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6000, name: '. 7000 OPERATING EXPENSES', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6010, name: 'Advertising Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6050, name: 'Amortization Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6100, name: 'Auto Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6150, name: 'Bad Debt Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6200, name: 'Bank Charges', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6250, name: 'Cash Over and Short', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6300, name: 'Commission Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6350, name: 'Depreciation Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6400, name: 'Employee Benefit Program', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6550, name: 'Freight Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6600, name: 'Gifts Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6650, name: 'Insurance General', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6700, name: 'Interest Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6750, name: 'Professional Fees', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6800, name: 'License Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6850, name: 'Maintenance Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6900, name: 'Meals and Entertainment', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 6950, name: 'Office Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 7000, name: 'Payroll Taxes', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 7050, name: 'Printing', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 7150, name: 'Postage', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 7200, name: 'Rent', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 7250, name: 'Repairs Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 7300, name: 'Salaries Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 7350, name: 'Supplies Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 7400, name: 'Taxes FIT Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 7500, name: 'Utilities Expense', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Account.create(number: 7900, name: 'Gain/Loss on Sale of Assets', active: 't', created_by: 1, updated_by: 1, account_type_id: 3)
Period.create(first_day: '2014-01-01', last_day: '2014-01-31', fiscal_year: 2014, number_in_fiscal_year: 1, open: 'f', created_by: 1, updated_by: 1)
Period.create(first_day: '2014-02-01', last_day: '2014-02-28', fiscal_year: 2014, number_in_fiscal_year: 2, open: 'f', created_by: 1, updated_by: 1)
Period.create(first_day: '2014-03-01', last_day: '2014-03-31', fiscal_year: 2014, number_in_fiscal_year: 3, open: 'f', created_by: 1, updated_by: 1)
Period.create(first_day: '2014-04-01', last_day: '2014-04-30', fiscal_year: 2014, number_in_fiscal_year: 4, open: 'f', created_by: 1, updated_by: 1)
Period.create(first_day: '2014-05-01', last_day: '2014-05-31', fiscal_year: 2014, number_in_fiscal_year: 5, open: 'f', created_by: 1, updated_by: 1)
Period.create(first_day: '2014-06-01', last_day: '2014-06-30', fiscal_year: 2014, number_in_fiscal_year: 6, open: 'f', created_by: 1, updated_by: 1)
Period.create(first_day: '2014-07-01', last_day: '2014-07-31', fiscal_year: 2014, number_in_fiscal_year: 7, open: 'f', created_by: 1, updated_by: 1)
Period.create(first_day: '2014-08-01', last_day: '2014-08-31', fiscal_year: 2014, number_in_fiscal_year: 8, open: 'f', created_by: 1, updated_by: 1)
Period.create(first_day: '2014-09-01', last_day: '2014-09-30', fiscal_year: 2014, number_in_fiscal_year: 9, open: 'f', created_by: 1, updated_by: 1)
Period.create(first_day: '2014-10-01', last_day: '2014-10-31', fiscal_year: 2014, number_in_fiscal_year: 10, open: 't', created_by: 1, updated_by: 1)
Period.create(first_day: '2014-11-01', last_day: '2014-11-30', fiscal_year: 2014, number_in_fiscal_year: 11,  open: 'f', created_by: 1, updated_by: 1)
Period.create(first_day: '2014-12-01', last_day: '2014-12-31', fiscal_year: 2014, number_in_fiscal_year: 12, open: 'f', created_by: 1, updated_by: 1)
