INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1000,'ASSETS','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1010,'Cash Operating Account','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1020,'Cash Debitors','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1030,'Cash Petty Cash','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1200,'RECEIVABLES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1210,'AR Trade','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1220,'AR Trade Notes Receivable','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1230,'AR Installment Receivables','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1240,'AR Retainage Withheld','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1290,'AR Allowance for Uncollectible Accounts','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1300,'INVENTORIES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1310,'Inventory Reserved','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1320,'Inventory Work-in-Progress','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1330,'Inventory Finished Goods','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1340,'Inventory Reservesd','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1350,'Inventory Unbilled Cost & Fees','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1390,'Inventory Reserve for Obsolescence','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1400,'Prepaid EXPENSES OTHER CURRENT ASSETS','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1410,'Prepaid Insurance','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1420,'Prepaid Real Estate Taxes','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1430,'Prepaid Repairs & Maintenance','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1440,'Prepaid Rent','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1450,'Prepaid Deposits','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1500,'PROPERTY PLANT EQUIPMENT','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1510,'PPE Buildings','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1520,'PPE Machinery & Equipment','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1530,'PPE Vehicles','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1540,'PPE Computer Equipment','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1550,'PPE Furniture & Fixtures','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1560,'PPE Leasehold Improvements','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1600,'ACCUMULATED DEPRECIATION AMORTIZATION','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1610,'ACCUM DEPR Buildings','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1620,'ACCUM DEPR Machinery Equipment','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1630,'ACCUM DEPR Vehicles','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1640,'ACCUM DEPR Computer Equipment','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1650,'ACCUM DEPR Furniture Fixtures','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1660,'ACCUM DEPR Leasehold Improvements','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1700,'NON CURRENT RECEIVABLES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1710,'NCA Notes Receivable','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1720,'NCA Installment Receivables','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1730,'NCA Retainage Withheld','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1800,'INTERCOMPANY RECEIVABLES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1900,'OTHER NON-CURRENT ASSETS','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1910,'Organization Costs','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1920,'Patents Licenses','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(1930,'Intangible Assets Capitalized Software Costs','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2000,'LIABILITIES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2100,'PAYABLES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2110,'A/P Trade','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2120,'A/P Accrued Accounts Payable','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2130,'A/P Retainage Withheld','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2150,'Current Maturities of Long-Term Debt','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2160,'Bank Notes Payable','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2170,'Construction Loans Payable','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2200,'ACCRUED COMPENSATION RELATED ITEMS','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2210,'Accrued Payroll','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2220,'Accrued Commissions','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2230,'Accrued FICA','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2240,'Accrued Unemployment Taxes','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2250,'Accrued Workmen.s Comp','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2260,'Accrued Medical Benefits','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2270,'Accrued 401 K Company Match','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2275,'W/H FICA','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2280,'W/H Medical Benefits','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2285,'W/H 401 K Employee Contribution','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2300,'OTHER ACCRUED EXPENSES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2310,'Accrued Rent','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2320,'Accrued Interest','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2330,'Accrued Property Taxes','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2340,'Accrued Warranty Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2500,'ACCRUED TAXES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2510,'Accrued Federal Income Taxes','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2520,'Accrued State Income Taxes','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2530,'Accrued Franchise Taxes','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2540,'Deferred FIT Current','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2550,'Deferred State Income Taxes','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2600,'DEFERRED TAXES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2610,'D/T FIT . NON CURRENT','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2620,'D/T SIT . NON CURRENT','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2700,'LONG-TERM DEBT','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2710,'LTD Notes Payable','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2720,'LTD Mortgages Payable','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2730,'LTD Installment Notes Payable','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2800,'INTERCOMPANY PAYABLES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(2900,'OTHER NON CURRENT LIABILITIES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(3000,'OWNERS EQUITIES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(3100,'Common Stock','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(3200,'Preferred Stock','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(3300,'Paid in Capital','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(3400,'Partners Capital','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(3500,'Member Contributions','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(3900,'Retained Earnings','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(4000,'REVENUE','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(4010,'REVENUE PRODUCT 1','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(4020,'REVENUE PRODUCT 2','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(4030,'REVENUE PRODUCT 3','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(4040,'REVENUE PRODUCT 4','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(4600,'Interest Income','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(4700,'Other Income','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(4800,'Finance Charge Income','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(4900,'Sales Returns and Allowances','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(4950,'Sales Discounts','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(5000,'COST OF GOODS SOLD','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(5010,'COGS PRODUCT 1','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(5020,'COGS PRODUCT 2','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(5030,'COGS PRODUCT 3','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(5040,'COGS PRODUCT 4','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(5700,'Freight','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(5800,'Inventory Adjustments','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(5900,'Purchase Returns and Allowances','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(5950,'Reserved','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6000,'. 7000 OPERATING EXPENSES','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6010,'Advertising Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6050,'Amortization Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6100,'Auto Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6150,'Bad Debt Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6200,'Bank Charges','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6250,'Cash Over and Short','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6300,'Commission Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6350,'Depreciation Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6400,'Employee Benefit Program','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6550,'Freight Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6600,'Gifts Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6650,'Insurance General','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6700,'Interest Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6750,'Professional Fees','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6800,'License Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6850,'Maintenance Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6900,'Meals and Entertainment','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(6950,'Office Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(7000,'Payroll Taxes','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(7050,'Printing','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(7150,'Postage','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(7200,'Rent','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(7250,'Repairs Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(7300,'Salaries Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(7350,'Supplies Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(7400,'Taxes FIT Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(7500,'Utilities Expense','t',1,1);
INSERT INTO accounts(account_number, name, active, created_by, updated_by) VALUES(7900,'Gain/Loss on Sale of Assets','t',1,1);
